kind: Service
apiVersion: v1
metadata:
  name: radarr
spec:
  selector:
    app: radarr
  ports:
  - protocol: TCP
    port: 7878
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: transmission
        image: lsioarmhf/radarr
        ports:
        - containerPort: 7878
        volumeMounts:
        - mountPath: /config
          name: radarr-config
        - mountPath: /downloads
          name: downloads
        - mountPath: /movies
          name: nfs-movies
        env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: nfs-movies
        persistentVolumeClaim:
          claimName: nfs-movies
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: radarr-config
    annotations:
        volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.20
    path: "/volume1/Movies"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
