apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.20
    path: "/volume1/Movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-series
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.20
    path: "/volume1/Series"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.20
    path: "/volume1/Backup"
