kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: downloads
    annotations:
        volume.beta.kubernetes.io/storage-class: slow
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
