- name: Add cgroup for CPU limits to bootparams
  lineinfile:
    dest: /boot/cmdline.txt
    regexp: '^(.*?)(\s*cgroup_enable=cpuset cgroup_enable=memory\s*)?$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    backrefs: true
    state: present
  tags: docker,docker-optimizations

- name: Change Docker options
  template: 
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker.service
  tags: docker,docker-optimizations
